#!/usr/bin/env python3
"""Does docs/checks.md list exactly the checks the tool runs?

Why this exists: docs/checks.md is generated by export-checks.ps1 and nothing in CI kept it honest.
It shipped the pre-0.6.0 wording all day once, then a mixed-language status column, then went one
check behind when usb-headset landed — three times, found by hand.

The obvious gate — regenerate and fail if the tree changed — cannot work, and that was measured rather
than assumed. Regenerating twice with no code change moves ten lines, because the generated table
embeds live results:

    - | 警告 | session-stale | 4 个到头显的通道仍是已建立状态（最早建立于 2 小时 56 分前） |
    + | 警告 | session-stale | 4 个到头显的通道仍是已建立状态（最早建立于 3 小时 12 分前） |
    - | 通过 | lan-reach     | 头显 192.168.11.14 可达（ping 1 ms，首次即应答）     |
    + | 通过 | lan-reach     | 头显 192.168.11.14 可达（ping 8 ms，首次即应答）     |

Those change every run by nature. A gate on the whole file would be red on every run, which is the same
as no gate — worse, because people learn to ignore red.

So this compares the part that must not drift: the set of check ids. A check added without the docs
regenerated is a failure; a ping that took 8 ms instead of 1 is not.

Usage:  python tools/check-docs-coverage.py
Exit:   0 in sync, 1 otherwise.
"""

from __future__ import annotations

import re
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
EXE = ROOT / "src" / "VdHelper" / "bin" / "Release" / "net10.0-windows" / "VdHelper.exe"
DOC = ROOT / "docs" / "checks.md"


def _force_utf8() -> None:
    for stream in (sys.stdout, sys.stderr):
        try:
            stream.reconfigure(encoding="utf-8", errors="replace")
        except (AttributeError, ValueError):
            pass


def tool_ids(text: str) -> set[str]:
    # Headings are the only place an id appears unambiguously in the report.
    return set(re.findall(r"#### \d+\. 【\S+?】`([a-z0-9-]+)`", text))


def doc_ids(text: str) -> set[str]:
    return set(re.findall(r"\*\*(?:\*\*)?([a-z][a-z0-9-]+)", text))


def main() -> int:
    _force_utf8()
    if not EXE.exists():
        print(f"找不到 {EXE} —— 先 dotnet build -c Release。", file=sys.stderr)
        return 1
    if not DOC.exists():
        print(f"找不到 {DOC}", file=sys.stderr)
        return 1

    with tempfile.TemporaryDirectory() as tmp:
        out = Path(tmp) / "r.md"
        subprocess.run([str(EXE), "--report", str(out)],
                       capture_output=True, text=True, encoding="utf-8", errors="replace")
        if not out.exists():
            print("体检没有产出报告，无法核对文档。", file=sys.stderr)
            return 1
        ran = tool_ids(out.read_text(encoding="utf-8", errors="replace"))

    documented = doc_ids(DOC.read_text(encoding="utf-8", errors="replace"))
    missing = sorted(ran - documented)
    extra = sorted(documented - ran)

    # The report prints some checks twice — once grouped by symptom class, once in full — so the
    # set is what matters, not the count.
    if missing or extra:
        print("docs coverage gate: FAIL", file=sys.stderr)
        if missing:
            print(f"  工具在跑、docs/checks.md 里没有：{missing}", file=sys.stderr)
        if extra:
            print(f"  docs/checks.md 列了、工具不跑：{extra}（可能被重命名了）", file=sys.stderr)
        print("\n跑 tools\\export-checks.ps1 与 tools\\export-docs-site.ps1，然后提交。", file=sys.stderr)
        return 1

    print(f"docs coverage gate: OK  {len(ran)} 个检测项与 docs/checks.md 一致")
    return 0


if __name__ == "__main__":
    sys.exit(main())